version: "3"

services:
  web:
    container_name: web
    build:
      context: .
      dockerfile: ./apps/web/Dockerfile
    ports:
      - 3000:3000
    networks:
      - coffee-tools-network
  api:
    container_name: api
    build:
      context: .
      dockerfile: ./apps/api/Dockerfile
    ports:
      - 3001:3001
    environment:
      - DATABASE_URL=postgres://postgres:postgres@postgres:5432/coffee_tools
    networks:
      - coffee-tools-network
    depends_on:
      - database
  database:
    container_name: postgres
    image: postgres:16
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=coffee_tools
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - coffee-tools-network

# Define a network, which allows containers to communicate
# with each other, by using their container name as a hostname
networks:
  coffee-tools-network:

volumes:
  postgres_data:
