version: "3"

services:
  web:
    container_name: web
    build:
      context: .
      dockerfile: ./apps/web/Dockerfile
    ports:
      - 3000:3000
    networks:
      - coffee-tools-network
  api:
    container_name: api
    build:
      context: .
      dockerfile: ./apps/api/Dockerfile
    ports:
      - 3001:3001
    networks:
      - coffee-tools-network

# Define a network, which allows containers to communicate
# with each other, by using their container name as a hostname
networks:
  coffee-tools-network:
